targets:
  $default:
    builders:
      hive_generator|hive_generator:
        generate_containers: true
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
          any_map: true
