// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LJ4YOlyyqRYLOrnr5ju2D8ypLD8l0CA',
    appId: '1:927243153328:web:cec3317679dcee74f6b075',
    messagingSenderId: '927243153328',
    projectId: 'expense-tracker-20441',
    authDomain: 'expense-tracker-20441.firebaseapp.com',
    storageBucket: 'expense-tracker-20441.firebasestorage.app',
    measurementId: 'G-867E069RV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEe5T0GvfMzKlNgsUyvuWbIU6-9ceY07g',
    appId: '1:927243153328:android:5b5386ade6bb1891f6b075',
    messagingSenderId: '927243153328',
    projectId: 'expense-tracker-20441',
    storageBucket: 'expense-tracker-20441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa3LnURYC_2eTcpcFHAYGfivU8p2uQEDY',
    appId: '1:927243153328:ios:7f4f925c2c3f1b1df6b075',
    messagingSenderId: '927243153328',
    projectId: 'expense-tracker-20441',
    storageBucket: 'expense-tracker-20441.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

}